- name: This playbook will install, configure and deploy web page into nginx
  hosts: all
  become: yes
  tasks: 
   - name: Install nginx web server
     apt: name=nginx state=latest update-cache=yes
   - name: Start the nginx web Server
     service: name=nginx state=started enabled=yes
